site_name: Valkyros Engine Documentation
site_description: >-
  Developer documentation for the Valkyros Engine, a AAA-grade, cross-platform 3D game engine using Vulkan and C++.
site_author: Thomas [YourNameHere]
site_url: http://localhost:8000/
repo_url: https://github.com/yourusername/valkyros
repo_name: GitHub
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: lime
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
nav:
  - Home: index.md
  - Overview:
      - Project Overview: 00_project_overview.md
      - Module Roadmap: 01_module_roadmap.md
      - From Primal to Valkyros: 02_primal_to_valkyros.md
      - Design Log: 03_design_log.md
  - Engine Design:
      - Graphics Pipeline: 04_graphics_pipeline.md
      - GUI Architecture: 05_gui_architecture.md
      - Design Docs Index: 01_design/index.md
  - Planning:
      - Timeline: 02_planning/timeline.md
  - Specs:
      - Specifications Index: 03_specs/index.md
  - Dev Logs:
      - DevLog Template: 04_devlogs/devlog_template.md
  - Technical Reference:
      - Tech Reference Index: 05_techref/index.md
  - Ideas:
      - Engine Ideas: 06_ideas/ideas.md
  - Meta:
      - Style Guide: style_guide.md
      - Build Notes: build_notes.md
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - awesome-pages
  - macros
  - mkdocs_macros
  - git-revision-date-localized
  - glightbox

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/valkyros
  version:
    provider: git
